name: deploy

on:
  push:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # some tests need access to Google Cloud Resources, e.g. Firestore
      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v0

      - name: Deploy Cloud Function
        run: gcloud functions deploy course-redirect --region europe-west3 --entry-point "Handle" --runtime go116 --trigger-http